apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Rich Deploy with CBCI
on:
  push:
    branches:
      - "**"
jobs:
  build-deploy:
    environment: stage
    steps:
      - uses: cloudbees-io/checkout@v1.0.2
        name: Checkout
        
      - uses: cloudbees-io/snyk-sca-scan-dependency@v1
        name: Snyk SCA scan
        with:
          orgname: ${{ vars.SNYK_SAAS_ORG_NAME }}
          token: ${{ secrets.SNYK_SAAS_TOKEN }}
          language: LANGUAGE_JAVA

      - uses: cloudbees-io/snyk-sast-scan-code@v1
        name: Snyk SAST Scan
        with:
          orgname: ${{ vars.SNYK_SAAS_ORG_NAME }}
          token: ${{ secrets.SNYK_SAAS_TOKEN }}
          language: LANGUAGE_JAVA

      - uses: cloudbees-io/cbci-run-job
        name: CBCI Deploy
        kind: deploy
        with:
          url: https://releaseiq.ironman.releaseiq.io/
          username: ${{ secrets.CBCI_IRONMAN_USERNAME }}
          password: ${{ secrets.CBCI_IRONMAN_PASSWORD }}
          job-name: demo_deploy_component4
          parameters: '{"TAG_NAME":"${{ cloudbees.scm.sha }}"}'